### ISSUE TITLE
missing 'use strict' break on node 4.2.3

### ISSUE THREAD

**Issue by mulyoved** [ndaidong/bella.js#14]
Get error: 
`stack=SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

from `bellajs/index.js:5:28`

so it fail to load `src/main.js`

Seem to me 'use strict' was removed in version 5.2 and this break when try to load bella.js

**Comment by ndaidong** [comment]
Hi @mulyoved, thank you for your feedback. 

In order to encourage people upgrade Node.js to the latest version and make use of the best ES6 features, BellaJS now is only available in Node.js v6.0.0 and newer.

**Comment by mulyoved** [comment]
Cannot use Node6 on production as not yet LTS, 
use bellajs through feed-reader which use bellajs@latest 
so build is broken
should use shrinkwrap

**Comment by ndaidong** [comment]
Sorry for the interruption. I will fix this issue as soon.

**Comment by ndaidong** [comment]
@mulyoved : Now you can install feed-reader@0.1.61 to get it works on node 4.

Cheers,
Dong
